# service1/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 495599739945.dkr.ecr.us-east-1.amazonaws.com/auth:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      imagePullSecrets:
        - name: ecr-registry-secret
