# service1/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: microservices
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # Use ClusterIP for internal services, LoadBalancer for external
  type: ClusterIP